services:
  web:
    image: ${APP_IMAGE}
    restart: unless-stopped
    volumes:
      - /var/lib/furnace/hints:/var/lib/furnace/hints
      - /var/lib/furnace/furnace.db:/var/lib/furnace/furnace.db
      - /var/lib/furnace/furnace.db-wal:/var/lib/furnace/furnace.db-wal
      - /var/lib/furnace/furnace.db-shm:/var/lib/furnace/furnace.db-shm
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
