services:
  web:
    image: ${APP_IMAGE}
    restart: unless-stopped
    volumes:
      - /etc/furnace/furnace.yaml:/etc/furnace/furnace.yaml:ro
      - /var/lib/furnace:/var/lib/furnace:ro
      - /var/lib/furnace/hints:/var/lib/furnace/hints
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
